# Generated by Django 6.0.6 on 2026-07-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SOCIETY_MANAGER", "Society Manager"),
                    ("RESIDENT", "Resident"),
                    ("VOLENTEER", "Volenteer"),
                    ("SECURITY", "Security"),
                ],
                default="RESIDENT",
                max_length=30,
            ),
        ),
    ]
