# Generated by Django 5.0.6 on 2026-07-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customuser_is_verified_alter_customuser_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerprofile",
            name="is_online",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="visibility_radius",
            field=models.FloatField(default=5000.0),
        ),
    ]
