# Generated by Django 5.0.6 on 2026-07-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0006_volunteerprofile_is_online_volunteerprofile_latitude_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="guardianprofile",
            name="guardian_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, null=True, unique=True
            ),
        ),
    ]
