# Generated by Django 5.0.6 on 2026-07-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_guardianprofile_guardian_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="volunteerprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=15, null=True
            ),
        ),
    ]
