# Generated by Django 6.0.6 on 2026-07-28 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_volunteerprofile_latitude_and_more"),
        ("society", "0002_alter_blocktower_options_alter_flat_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardianprofile",
            name="id_proof",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/guardian_id/"
            ),
        ),
        migrations.AddField(
            model_name="guardianprofile",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guardianprofile",
            name="verification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guardianprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="guardianprofile",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_guardians",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="residentprofile",
            name="aadhaar_card",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/aadhaar/"
            ),
        ),
        migrations.AddField(
            model_name="residentprofile",
            name="driving_license",
            field=models.FileField(blank=True, null=True, upload_to="documents/dl/"),
        ),
        migrations.AddField(
            model_name="residentprofile",
            name="profile_photo",
            field=models.FileField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="residentprofile",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="residentprofile",
            name="society_id_card",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/society_id/"
            ),
        ),
        migrations.AddField(
            model_name="residentprofile",
            name="verification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="residentprofile",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_residents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="securityprofile",
            name="assigned_block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_staff",
                to="society.blocktower",
            ),
        ),
        migrations.AddField(
            model_name="securityprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="securityprofile",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Suspended", "Suspended"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="securityprofile",
            name="id_proof",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/security_id/"
            ),
        ),
        migrations.AddField(
            model_name="securityprofile",
            name="profile_photo",
            field=models.FileField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="securityprofile",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityprofile",
            name="verification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="securityprofile",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_security",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="assigned_block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_volunteers",
                to="society.blocktower",
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="assigned_society",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_volunteers",
                to="society.society",
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="emergency_training",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="id_proof",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/volunteer_id/"
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="profile_photo",
            field=models.FileField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Suspended", "Suspended"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="verification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_volunteers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("Aadhaar", "Aadhaar Card"),
                            ("Driving License", "Driving License"),
                            ("Employee ID", "Employee ID"),
                            ("Society ID", "Society ID"),
                            ("Profile Photo", "Profile Photo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/user_docs/")),
                ("title", models.CharField(blank=True, max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
