# Generated by Django 5.0.6 on 2026-07-30 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_guardianprofile_id_proof_guardianprofile_remarks_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDirectoryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public (Society Wide)"),
                            ("RESPONDERS", "Responders Only"),
                            ("GUARDIANS_ONLY", "Linked Guardians Only"),
                            ("PRIVATE", "Private (Admin Only)"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_emergency_contact", models.BooleanField(default=False)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("PHONE", "Phone"),
                            ("EMAIL", "Email"),
                            ("APP_CHAT", "App Chat"),
                        ],
                        default="PHONE",
                        max_length=20,
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=255, null=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directory_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Directory Profile",
                "verbose_name_plural": "User Directory Profiles",
            },
        ),
    ]
