# Generated by Django 5.0.6 on 2026-08-07 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_userdirectoryprofile"),
        ("sos", "0016_broadcastlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityprofile",
            name="current_incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_security_profiles",
                to="sos.sosincident",
            ),
        ),
        migrations.AddField(
            model_name="securityprofile",
            name="duty_status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("ON_DUTY", "On Duty"),
                    ("BUSY", "Busy"),
                    ("RESPONDING", "Responding"),
                    ("OFFLINE", "Offline"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="securityprofile",
            name="is_on_duty",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="securityprofile",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="securityprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="securityprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("ONLINE", "Online"),
                    ("OFFLINE", "Offline"),
                    ("BUSY", "Busy"),
                    ("UNAVAILABLE", "Unavailable"),
                ],
                default="ONLINE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
