# Generated by Django 5.0.6 on 2026-07-14 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        ("sos", "0002_add_meta_indexes_and_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="sos.sosincident",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(default="LOW", max_length=20),
        ),
    ]
