# Generated by Django 5.0.6 on 2026-07-23 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_notificationtemplate_fcmdevice_notificationlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationtemplate",
            name="email_template",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="push_template",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="sms_template",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="subject_template",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="message_template",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="title_template",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_number", models.CharField(max_length=30)),
                ("message", models.TextField()),
                ("provider", models.CharField(default="CONSOLE", max_length=50)),
                ("status", models.CharField(default="SENT", max_length=20)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
