# Generated by Django 5.0.6 on 2026-07-23 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_notificationtemplate_email_template_and_more"),
        ("sos", "0006_sosincident_emergency_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="delivery_channel",
            field=models.CharField(default="IN_APP", max_length=20),
        ),
        migrations.AddField(
            model_name="notification",
            name="delivery_status",
            field=models.CharField(default="SENT", max_length=20),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(default="SOS_CREATED", max_length=50),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient_role",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user"], name="notificatio_user_id_c291d5_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_46ad24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["is_read"], name="notificatio_is_read_9edb86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["priority"], name="notificatio_priorit_bf8ea0_idx"
            ),
        ),
    ]
