# Generated by Django 5.0.6 on 2026-08-06 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_alter_notification_options_and_more"),
        ("sos", "0014_sosincident_city_sosincident_country_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="failure_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_logs",
                to="sos.sosincident",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="provider_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["channel"], name="notificatio_channel_e46ef2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(fields=["status"], name="notificatio_status_a242db_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_01830a_idx"
            ),
        ),
    ]
