# Generated by Django 5.0.6 on 2026-07-14 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emergencycategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Emergency Category",
                "verbose_name_plural": "Emergency Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="sosincident",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "SOS Incident",
                "verbose_name_plural": "SOS Incidents",
            },
        ),
        migrations.AddIndex(
            model_name="sosincident",
            index=models.Index(fields=["status"], name="sos_sosinci_status_bc9390_idx"),
        ),
        migrations.AddIndex(
            model_name="sosincident",
            index=models.Index(
                fields=["resident"], name="sos_sosinci_residen_2f9cb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sosincident",
            index=models.Index(
                fields=["created_at"], name="sos_sosinci_created_e89425_idx"
            ),
        ),
    ]
