# Generated by Django 5.0.6 on 2026-07-14 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sos", "0002_add_meta_indexes_and_ordering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sosincident",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "LOW"),
                    ("MEDIUM", "MEDIUM"),
                    ("HIGH", "HIGH"),
                    ("CRITICAL", "CRITICAL"),
                ],
                default="HIGH",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SOSEmergencyMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="sos.sosincident",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sos_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SOS Emergency Message",
                "verbose_name_plural": "SOS Emergency Messages",
                "ordering": ["created_at"],
            },
        ),
    ]
