# Generated by Django 5.0.6 on 2026-07-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sos", "0005_alter_sosincident_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sosincident",
            name="emergency_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="voice_message",
            field=models.FileField(blank=True, null=True, upload_to="voice_messages/"),
        ),
    ]
