# Generated by Django 5.0.6 on 2026-07-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sos", "0006_sosincident_emergency_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="escalationconfig",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="escalationconfig",
            name="escalation_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="escalationconfig",
            name="notify_admin",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="escalationconfig",
            name="notify_security",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="escalationconfig",
            name="notify_volunteers",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="escalationconfig",
            name="response_time_minutes",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="escalationconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="escalationlog",
            name="escalation_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="escalationlog",
            name="new_recipient",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="escalationlog",
            name="previous_recipient",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="escalationlog",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escalationlog",
            name="response_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
