# Generated by Django 5.0.6 on 2026-07-30 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sos", "0008_sosincident_accepted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sosincident",
            name="active_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_incidents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="closure_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="closure_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("OPEN", "OPEN"),
                    ("ACTIVE", "ACTIVE"),
                    ("ESCALATED", "ESCALATED"),
                    ("RESOLVED", "RESOLVED"),
                    ("CLOSED", "CLOSED"),
                ],
                db_index=True,
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="last_status_changed_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="opened_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="resolution_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_incidents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sosincident",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Assigned", "Assigned"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                    ("Cancelled", "Cancelled"),
                    ("OPEN", "OPEN"),
                    ("ACTIVE", "ACTIVE"),
                    ("ESCALATED", "ESCALATED"),
                    ("RESOLVED", "RESOLVED"),
                    ("CLOSED", "CLOSED"),
                ],
                db_index=True,
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="IncidentStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(max_length=50)),
                ("new_status", models.CharField(max_length=50)),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incident_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="sos.sosincident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident Status Log",
                "verbose_name_plural": "Incident Status Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
