# Generated by Django 5.0.6 on 2026-07-30 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sos", "0009_sosincident_active_at_sosincident_closed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_role",
                    models.CharField(
                        choices=[
                            ("RESIDENT", "RESIDENT"),
                            ("GUARDIAN", "GUARDIAN"),
                            ("VOLUNTEER", "VOLUNTEER"),
                            ("SECURITY", "SECURITY"),
                            ("ADMIN", "ADMIN"),
                            ("SYSTEM", "SYSTEM"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "TEXT"),
                            ("SYSTEM", "SYSTEM"),
                            ("IMAGE", "IMAGE"),
                            ("LOCATION", "LOCATION"),
                            ("VOICE", "VOICE"),
                            ("FILE", "FILE"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="chat_attachments/%Y/%m/%d/"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="sos.sosincident",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="sos.incidentchatmessage",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident Chat Message",
                "verbose_name_plural": "Incident Chat Messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["incident", "created_at"],
                        name="sos_inciden_inciden_3ade4a_idx",
                    ),
                    models.Index(
                        fields=["sender"], name="sos_inciden_sender__ca521a_idx"
                    ),
                    models.Index(
                        fields=["message_type"], name="sos_inciden_message_386d14_idx"
                    ),
                ],
            },
        ),
    ]
