# Generated by Django 5.0.6 on 2026-07-30 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sos", "0010_incidentchatmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentResponseUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("RESIDENT", "RESIDENT"),
                            ("GUARDIAN", "GUARDIAN"),
                            ("VOLUNTEER", "VOLUNTEER"),
                            ("SECURITY", "SECURITY"),
                            ("ADMIN", "ADMIN"),
                            ("SYSTEM", "SYSTEM"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "TEXT"),
                            ("STATUS", "STATUS"),
                            ("ARRIVAL", "ARRIVAL"),
                            ("MEDICAL", "MEDICAL"),
                            ("SECURITY", "SECURITY"),
                            ("NOTE", "NOTE"),
                            ("SYSTEM", "SYSTEM"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "PUBLIC"),
                            ("RESPONDERS", "RESPONDERS"),
                            ("GUARDIANS", "GUARDIANS"),
                            ("INTERNAL", "INTERNAL"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="response_updates/%Y/%m/%d/"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incident_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_updates",
                        to="sos.sosincident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident Response Update",
                "verbose_name_plural": "Incident Response Updates",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["incident", "created_at"],
                        name="sos_inciden_inciden_c76f03_idx",
                    ),
                    models.Index(
                        fields=["author"], name="sos_inciden_author__0de18a_idx"
                    ),
                    models.Index(fields=["role"], name="sos_inciden_role_464ccf_idx"),
                    models.Index(
                        fields=["visibility"], name="sos_inciden_visibil_50d535_idx"
                    ),
                ],
            },
        ),
    ]
