# Generated by Django 5.0.6 on 2026-07-30 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sos", "0011_incidentresponseupdate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityIncidentResolutionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resolution_summary", models.TextField()),
                ("actions_taken", models.TextField(blank=True, default="")),
                ("medical_assistance", models.BooleanField(default=False)),
                ("police_assistance", models.BooleanField(default=False)),
                ("fire_assistance", models.BooleanField(default=False)),
                ("property_damage", models.BooleanField(default=False)),
                ("casualties", models.IntegerField(default=0)),
                ("additional_notes", models.TextField(blank=True, null=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="resolutions/%Y/%m/%d/"
                    ),
                ),
                ("resolved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_resolution_report",
                        to="sos.sosincident",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_security_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Incident Resolution Report",
                "verbose_name_plural": "Security Incident Resolution Reports",
            },
        ),
    ]
