# Generated by Django 5.0.6 on 2026-08-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sos", "0012_securityincidentresolutionreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="sosincident",
            name="voice_duration",
            field=models.IntegerField(
                blank=True, help_text="Duration in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="voice_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
