# Generated by Django 5.0.6 on 2026-08-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sos", "0013_sosincident_voice_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sosincident",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="pincode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="sosincident",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
