# Generated by Django 5.0.6 on 2026-08-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sos", "0014_sosincident_city_sosincident_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="escalationconfig",
            name="secondary_guardian_delay",
            field=models.IntegerField(
                default=60,
                help_text="Delay in seconds before secondary guardian escalation",
            ),
        ),
        migrations.AddField(
            model_name="escalationconfig",
            name="security_delay",
            field=models.IntegerField(
                default=120,
                help_text="Delay in seconds before security staff escalation",
            ),
        ),
        migrations.AddField(
            model_name="escalationconfig",
            name="volunteer_delay",
            field=models.IntegerField(
                default=180,
                help_text="Delay in seconds before community volunteer escalation",
            ),
        ),
        migrations.AddField(
            model_name="escalationlog",
            name="duration",
            field=models.IntegerField(
                default=0, help_text="Elapsed time in seconds before escalation"
            ),
        ),
        migrations.AddField(
            model_name="escalationlog",
            name="triggered_by",
            field=models.CharField(default="SYSTEM", max_length=100),
        ),
    ]
