# Generated by Django 5.0.6 on 2026-08-07 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sos", "0015_escalationconfig_secondary_guardian_delay_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        choices=[
                            ("VOLUNTEER", "Volunteer"),
                            ("SECURITY", "Security"),
                            ("GUARDIAN", "Guardian"),
                            ("ADMIN", "Admin"),
                            ("ALL", "All Responders"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("radius_km", models.FloatField(default=5.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("NO_RESPONDERS_NEARBY", "No Responders Nearby"),
                            ("PARTIALLY_DELIVERED", "Partially Delivered"),
                        ],
                        default="SUCCESS",
                        max_length=30,
                    ),
                ),
                ("delivery_channel", models.CharField(default="IN_APP", max_length=50)),
                ("message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_logs",
                        to="sos.sosincident",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Broadcast Log",
                "verbose_name_plural": "Broadcast Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["incident", "created_at"],
                        name="sos_broadca_inciden_35b04a_idx",
                    ),
                    models.Index(
                        fields=["target_role"], name="sos_broadca_target__326532_idx"
                    ),
                    models.Index(
                        fields=["status"], name="sos_broadca_status_a75b1e_idx"
                    ),
                ],
            },
        ),
    ]
