# Generated by Django 6.0.6 on 2026-07-28 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("society", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blocktower",
            options={
                "ordering": ["name"],
                "verbose_name": "Block / Wing",
                "verbose_name_plural": "Blocks / Wings",
            },
        ),
        migrations.AlterModelOptions(
            name="flat",
            options={"ordering": ["flat_number"]},
        ),
        migrations.AlterModelOptions(
            name="society",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Societies"},
        ),
        migrations.AddField(
            model_name="blocktower",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="blocktower",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="blocktower",
            name="total_flats",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flat",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="flat",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_flats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flat",
            name="owner_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="flat",
            name="resident_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="flat",
            name="resident_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occupied_flats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="society",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="society",
            name="number_of_blocks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="society",
            name="society_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_societies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="society",
            name="total_flats",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="society",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blocktower",
            name="total_floors",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="flat",
            name="floor",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="flat",
            name="type",
            field=models.CharField(default="2BHK", max_length=50),
        ),
        migrations.AlterField(
            model_name="society",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="society",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="society",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
