# Generated by Django 6.0.6 on 2026-07-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("society", "0002_alter_blocktower_options_alter_flat_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="society",
            name="country",
            field=models.CharField(default="India", max_length=100),
        ),
        migrations.AddField(
            model_name="society",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="society",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="society",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="society",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
