import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('hi'),
    Locale('te'),
    Locale('ta'),
    Locale('kn'),
    Locale('ml'),
    Locale('es'),
    Locale('fr'),
    Locale('de'),
    Locale('it'),
    Locale('pt'),
    Locale('ru'),
    Locale('tr'),
    Locale('ar'),
    Locale('zh'),
    Locale('ja'),
    Locale('ko'),
    Locale('th'),
    Locale('vi'),
    Locale('id'),
  ];

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'CareConnect',
      'tagline': 'Community Emergency Response & Assistance Network',
      'subHeading': 'Protecting Communities, One SOS at a Time.',
      'getStarted': 'Get Started',
      'login': 'Login',
      'register': 'Register',
      'welcomeBack': 'Welcome Back',
      'email': 'Email Address',
      'password': 'Password',
      'rememberMe': 'Remember Me',
      'forgotPassword': 'Forgot Password?',
      'createAccount': 'Create Account',
      'chooseLanguage': 'Choose Your Language',
      'selectLanguageSub': 'Select your preferred language for CareConnect.',
      'continueText': 'Continue',
      'oneTapSos': 'One-Tap SOS',
      'oneTapSosSub': 'Instant emergency assistance at your fingertips.',
      'guardianAlerts': 'Guardian Alerts',
      'guardianAlertsSub': 'Notify trusted guardians immediately.',
      'liveGps': 'Live GPS Tracking',
      'liveGpsSub': 'Share accurate emergency location in real-time.',
      'volunteerResponse': 'Volunteer Response',
      'volunteerResponseSub': 'Nearby volunteers receive instant alerts.',
      'securityCoordination': 'Security Coordination',
      'securityCoordinationSub': 'Security staff receive instant notifications.',
      'emergencyChat': 'Emergency Chat',
      'emergencyChatSub': 'Real-time communication during emergencies.',
      'communitySafety': 'Community Safety',
      'communitySafetySub': 'Integrated society emergency response.',
      'howItWorks': 'How It Works',
      'step1': 'Register',
      'step2': 'Join Society',
      'step3': 'Add Guardians',
      'step4': 'Press SOS',
      'step5': 'Receive Help',
      'settings': 'Settings',
      'language': 'Language',
      'privacyPolicy': 'Privacy Policy',
      'termsConditions': 'Terms & Conditions',
      'version': 'Version 1.0.0 (Production Build)',
      'description': 'CareConnect enables residents, guardians, volunteers, security personnel, and administrators to respond quickly during emergencies through intelligent SOS routing, real-time communication, and coordinated community response.',
      
      // Registration Keys
      'step1PersonalDetails': 'Step 1: Enter your personal details',
      'step2RoleConfig': 'Step 2: Choose and configure your profile role',
      'step3ConfirmDetails': 'Step 3: Confirm details and register',
      'fullName': 'Full Name',
      'confirmPassword': 'Confirm Password',
      'passwordsDoNotMatch': 'Passwords do not match',
      'chooseYourRole': 'Choose your role',
      'residentRole': 'Resident',
      'guardianRole': 'Guardian',
      'volunteerRole': 'Volunteer',
      'securityRole': 'Security Staff',
      'selectSociety': 'Select Society',
      'selectBlock': 'Select Block',
      'flatApartmentNumber': 'Flat/Apartment Number',
      'selectRelationship': 'Select Relationship',
      'skills': 'Skills (e.g. Medical, First Aid)',

      // Day 17 Localization Keys
      'contactDirectory': 'Contact Directory',
      'trustedCommunityContacts': 'Trusted community contacts',
      'searchContacts': 'Search by name, role, phone...',
      'noContactsFound': 'No contacts found.',
      'responseUpdates': 'Response Updates',
      'incidentUpdates': 'Incident Updates',
      'incidentCreated': 'Emergency incident created.',
      'guardianAccepted': 'Guardian accepted the incident.',
      'volunteerAssigned': 'Volunteer assigned.',
      'securityAssigned': 'Security responder assigned.',
      'responderArrived': 'Responder arrived.',
      'incidentEscalated': 'Incident escalated.',
      'incidentResolved': 'Incident resolved.',
      'incidentClosed': 'Incident closed.',
      'callContact': 'Call',
      'messageContact': 'Message',
      'phoneMaskedNotice': 'Phone number is masked due to privacy settings.',

      // Day 18 Localization Keys
      'securityOperationsCommand': 'Security Operations Command',
      'activeEmergencies': 'ACTIVE EMERGENCIES',
      'assignedResponders': 'ASSIGNED RESPONDERS',
      'avgResponseTime': 'AVG RESPONSE TIME',
      'resolvedToday': 'RESOLVED TODAY',
      'activeSecurityIncidents': 'Active Security Incidents',
      'noActiveIncidents': 'No active incidents reported.',
      'responseCoordination': 'Response Coordination',
      'acceptIncident': 'Accept Incident',
      'markResponding': 'Mark Responding',
      'markArrived': 'Mark Arrived',
      'requestBackup': 'Request Backup',
      'resolveIncident': 'Resolve Incident',
      'securityActions': 'Security Response Actions',
      'statusUpdatedTo': 'Status updated to',
      'incidentAcceptedBySecurity': 'Incident accepted by security responder.',
      'responderArrivalStatus': 'Responder Arrival & Status',
      'guardianNotified': 'Guardian Notified',
      'securityStatus': 'Security Status',
      'volunteerStatus': 'Volunteer Status',
      'responseUpdatesTimeline': 'View response update feed',
      'formalResolutionReport': 'Formal Resolution Report',
      'resolutionSummaryRequired': 'Resolution summary is required',
      'actionsTakenBySecurity': 'Actions Taken by Security Team',
      'confirmIncidentResolution': 'Confirm Incident Resolution',
      'availability': 'Availability (e.g. Weekends, 24/7)',
      'serviceArea': 'Service Area (e.g. Block A, Outer)',
      'shift': 'Shift (e.g. Day, Night)',
      'employeeId': 'Employee ID',
      'assignedSociety': 'Assigned Society',
      'reviewRegistrationSummary': 'Review Registration Summary',
      'agreeTermsText': 'I agree to the Terms & Privacy Policy',
      'addContact': 'Add Emergency Contact',
      'addGuardian': 'Add Guardian',
      'linkGuardian': 'Link Guardian with Code',
      'enterGuardianCode': 'Enter Guardian Code',
      
      // Common UI & Navigation
      'home': 'Home',
      'alerts': 'Alerts',
      'profile': 'Profile',
      'logout': 'Logout',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'save': 'Save',
      'close': 'Close',
      'back': 'Back',
      'loading': 'Loading...',
      'search': 'Search...',
      'error': 'Error',
      'success': 'Success',
      'warning': 'Warning',
      'info': 'Information',

      // Dashboards & Roles
      'residentDashboard': 'Resident Dashboard',
      'guardianDashboard': 'Guardian Dashboard',
      'volunteerDashboard': 'Volunteer Dashboard',
      'securityDashboard': 'Security Dashboard',
      'adminDashboard': 'Admin Dashboard',
      'societyManager': 'Society Manager',
      'dutyStatus': 'Duty Status',
      'online': 'Online & Available',
      'offline': 'Offline',
      'inProgressIncident': 'In Progress',
      'viewDetails': 'View Details',
      'callResident': 'Call Resident',
      'openChat': 'Open Emergency Chat',
      'responseFeed': 'Response Timeline',

      // SOS Panic & Category Workflow
      'emergencyType': 'Emergency Category',
      'medical': 'Medical Emergency',
      'fire': 'Fire Outbreak',
      'security': 'Security Threat',
      'lift': 'Lift Trap / Malfunction',
      'disaster': 'Natural Disaster',
      'general': 'General Emergency',
      'recordVoiceMessage': 'Record Voice Note',
      'stopRecording': 'Stop Recording',
      'playVoiceMessage': 'Play Voice Note',
      'deleteVoiceMessage': 'Delete Voice Note',
      'currentLocation': 'Current Location',
      'confirmSos': 'Confirm & Send SOS',
      'sosSuccess': 'SOS Broadcast Sent!',
      'respondersNotified': 'Guardians, nearby volunteers, and security have been alerted.',

      // Society & Contacts
      'societyName': 'Society',
      'blockName': 'Block',
      'flatNumber': 'Flat',
      'guardianCode': 'Guardian Code',
      'generateCode': 'Generate Code',
      'relationship': 'Relationship',
      'primaryGuardian': 'Primary Guardian',
      // Forgot Password & Reset Flow Keys
      'enterRegisteredEmailSub': 'Enter your registered email address and we will send you a verification code.',
      'sendOtp': 'Send Verification Code',
      'otpVerificationTitle': 'OTP Verification',
      'weSentCodeTo': 'We sent a 6-digit verification code to',
      'codeExpiresIn': 'Code expires in',
      'otpExpired': 'OTP expired. Request a new code.',
      'resendCodeIn': 'Resend code in',
      'resendCode': 'Resend Code',
      'verifyOtp': 'Verify Code',
      'newPassword': 'New Password',
      'confirmPasswordLabel': 'Confirm New Password',
      'createStrongPasswordSub': 'Create a strong new password for your account.',
      'passwordResetSuccessfulTitle': 'Password Reset Successful',
      'passwordResetSuccessfulSub': 'Your password has been updated successfully.',
      'backToLogin': 'Back to Sign In',
      'passwordMismatch': 'New password and confirmation password do not match.',
      'passwordTooWeak': 'Password must be at least 8 characters long.',
    },
    'hi': {
      'appName': 'CareConnect',
      'tagline': 'सामुदायिक आपातकालीन प्रतिक्रिया और सहायता नेटवर्क',
      'subHeading': 'समुदायों की सुरक्षा, एक समय में एक एसओएस।',
      'getStarted': 'शुरू करें',
      'login': 'लॉग इन करें',
      'register': 'पंजीकरण करें',
      'welcomeBack': 'वापसी पर आपका स्वागत है',
      'email': 'ईमेल पता',
      'password': 'पासवर्ड',
      'rememberMe': 'मुझे याद रखें',
      'forgotPassword': 'पासवर्ड भूल गए?',
      'createAccount': 'खाता बनाएं',
      'chooseLanguage': 'अपनी भाषा चुनें',
      'selectLanguageSub': 'CareConnect के लिए अपनी पसंदीदा भाषा चुनें।',
      'continueText': 'जारी रखें',
      'oneTapSos': 'वन-टैप एसओएस',
      'oneTapSosSub': 'आपकी उंगलियों पर त्वरित आपातकालीन सहायता।',
      'guardianAlerts': 'अभिभावक अलर्ट',
      'guardianAlertsSub': 'विश्वसनीय अभिभावकों को तुरंत सूचित करें।',
      'liveGps': 'लाइव जीपीएस ट्रैकिंग',
      'liveGpsSub': 'वास्तविक समय में सटीक आपातकालीन स्थान साझा करें।',
      'volunteerResponse': 'स्वयंसेवक प्रतिक्रिया',
      'volunteerResponseSub': 'पास के स्वयंसेवकों को तुरंत अलर्ट प्राप्त होते हैं।',
      'securityCoordination': 'सुरक्षा समन्वय',
      'securityCoordinationSub': 'सुरक्षा कर्मचारियों को तत्काल सूचनाएं मिलती हैं।',
      'emergencyChat': 'आपातकालीन चैट',
      'emergencyChatSub': 'आपात स्थिति के दौरान वास्तविक समय संचार।',
      'communitySafety': 'सामुदायिक सुरक्षा',
      'communitySafetySub': 'एकीकृत समाज आपातकालीन प्रतिक्रिया।',
      'howItWorks': 'यह कैसे काम करता है',
      'step1': 'पंजीकरण',
      'step2': 'सोसायटी में शामिल हों',
      'step3': 'अभिभावक जोड़ें',
      'step4': 'एसओएस दबाएं',
      'step5': 'सहायता प्राप्त करें',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'privacyPolicy': 'गोपनीयता नीति',
      'termsConditions': 'नियम एवं शर्तें',
      'version': 'संस्करण 1.0.0 (उत्पादन बिल्ड)',
      'description': 'CareConnect निवासियों, अभिभावकों, स्वयंसेवकों, सुरक्षा कर्मियों और प्रशासकों को बुद्धिमान एसओएस राउटिंग के माध्यम से आपात स्थिति के दौरान जल्दी प्रतिक्रिया देने में सक्षम बनाता है।',
      'home': 'होम',
      'alerts': 'अलर्ट',
      'profile': 'प्रोफ़ाइल',
      'logout': 'लॉग आउट',
      'submit': 'सबमिट करें',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'close': 'बंद करें',
      'back': 'पीछे',
      'loading': 'लोड हो रहा है...',
      'search': 'खोजें...',
      'error': 'त्रुटि',
      'success': 'सफलता',
      'warning': 'चेतावनी',
      'info': 'जानकारी',
      'residentDashboard': 'निवासी डैशबोर्ड',
      'guardianDashboard': 'अभिभावक डैशबोर्ड',
      'volunteerDashboard': 'स्वयंसेवक डैशबोर्ड',
      'securityDashboard': 'सुरक्षा डैशबोर्ड',
      'dutyStatus': 'ड्यूटी स्थिति',
      'online': 'ऑनलाइन उपलब्ध',
      'offline': 'ऑफ़लाइन',
      'acceptIncident': 'घटना स्वीकार करें',
      'inProgressIncident': 'प्रगति पर है',
      'resolveIncident': 'समाधान करें',
      'viewDetails': 'विवरण देखें',
      'callResident': 'निवासी को कॉल करें',
      'openChat': 'आपातकालीन चैट खोलें',
      'emergencyType': 'आपातकालीन श्रेणी',
      'medical': 'चिकित्सा आपातकाल',
      'fire': 'आग की घटना',
      'security': 'सुरक्षा खतरा',
      'lift': 'लिफ्ट की खराबी',
      'disaster': 'प्राकृतिक आपदा',
      'general': 'सामान्य आपातकाल',
      'recordVoiceMessage': 'वॉयस नोट रिकॉर्ड करें',
      'stopRecording': 'रिकॉर्डिंग रोकें',
      'confirmSos': 'एसओएस भेजें',
      'sosSuccess': 'एसओएस भेजा गया!',
      'respondersNotified': 'अभिभावकों और सुरक्षा को सतर्क कर दिया गया है।',
      'societyName': 'सोसायटी',
      'blockName': 'ब्लॉक',
      'flatNumber': 'फ्लैट',
      'guardianCode': 'अभिभावक कोड',
      'generateCode': 'कोड जनरेट करें',
      'linkGuardian': 'अभिभावक जोड़ें',
      'relationship': 'संबंध',
      'primaryGuardian': 'प्राथमिक अभिभावक',
      'secondaryGuardian': 'द्वितीयक अभिभावक',
      'emergencyContact': 'आपातकालीन संपर्क',
    },
    'te': {
      'appName': 'CareConnect',
      'tagline': 'కమ్యూనిటీ ఎమర్జెన్సీ రెస్పాన్స్ & అసిస్టెన్స్ నెట్‌వర్క్',
      'subHeading': 'సమాజ రక్షణ, ఒకేసారి ఒక SOS.',
      'getStarted': 'ప్రారంభించండి',
      'login': 'లాగిన్',
      'register': 'రిజిస్టర్',
      'welcomeBack': 'స్వాగతం',
      'email': 'ఈమెయిల్ చిరునామా',
      'password': 'పాస్‌వర్డ్',
      'rememberMe': 'నన్ను గుర్తుంచుకో',
      'forgotPassword': 'పాస్‌వర్డ్ మర్చిపోయారా?',
      'createAccount': 'ఖాతాను సృష్టించండి',
      'chooseLanguage': 'మీ భాషను ఎంచుకోండి',
      'selectLanguageSub': 'CareConnect కోసం మీ ప్రాధాన్య భాషను ఎంచుకోండి.',
      'continueText': 'కొనసాగించండి',
      'oneTapSos': 'వన్-టాప్ SOS',
      'oneTapSosSub': 'మీ వేలిముద్రల వద్ద తక్షణ అత్యవసర సహాయం.',
      'guardianAlerts': 'గార్డియన్ అలర్ట్‌లు',
      'guardianAlertsSub': 'విశ్వసనీయ గార్డియన్లకు వెంటనే నివేదించండి.',
      'liveGps': 'లైవ్ GPS ట్రాకింగ్',
      'liveGpsSub': 'నిజ సమయంలో ఖచ్చితమైన అత్యవసర స్థానాన్ని పంచుకోండి.',
      'volunteerResponse': 'వాలంటీర్ స్పందన',
      'volunteerResponseSub': 'సమీపంలోని వాలంటీర్లు తక్షణ అలర్ట్‌లను అందుకుంటారు.',
      'securityCoordination': 'సెక్యూరిటీ సమన్వయం',
      'securityCoordinationSub': 'సెక్యూరిటీ సిబ్బందికి తక్షణ సమాచారం లభిస్తుంది.',
      'emergencyChat': 'అత్యవసర చాట్',
      'emergencyChatSub': 'అత్యవసర సమయంలో నిజ సమయ సమాచారం.',
      'communitySafety': 'కమ్యూనిటీ భద్రత',
      'communitySafetySub': 'సమన్వయ సమాజ అత్యవసర స్పందన.',
      'howItWorks': 'ఇది ఎలా పనిచేస్తుంది',
      'step1': 'రిజిస్టర్ చేయండి',
      'step2': 'సొసైటీలో చేరండి',
      'step3': 'గార్డియన్లను జోడించండి',
      'step4': 'SOS నొక్కండి',
      'step5': 'సహాయం పొందండి',
      'settings': 'సెట్టింగ్‌లు',
      'language': 'భాష',
      'privacyPolicy': 'గోప్యతా విధానం',
      'termsConditions': 'నిబంధనలు & షరతులు',
      'version': 'వెర్షన్ 1.0.0 (ప్రొడక్షన్ బిల్డ్)',
      'description': 'CareConnect నివాసితులు, గార్డియన్లు, వాలంటీర్లు మరియు సెక్యూరిటీ సిబ్బందికి అత్యవసర సమయాల్లో తక్షణ సహాయం అందిస్తుంది.',
      'home': 'హోమ్',
      'alerts': 'అలర్ట్‌లు',
      'profile': 'ప్రొఫైల్',
      'logout': 'లాగ్ అవుట్',
      'submit': 'సబ్‌మిట్',
      'cancel': 'రద్దు చేయి',
      'save': 'సేవ్ చేయి',
      'close': 'మూసివేయి',
      'back': 'వెనుకకు',
      'loading': 'లోడ్ అవుతోంది...',
      'search': 'శోధించండి...',
      'error': 'లోపం',
      'success': 'విజయం',
      'warning': 'హెచ్చరిక',
      'info': 'సమాచారం',
      'residentDashboard': 'నివాసి డాష్‌బోర్డ్',
      'guardianDashboard': 'గార్డియన్ డాష్‌బోర్డ్',
      'volunteerDashboard': 'వాలంటీర్ డాష్‌బోర్డ్',
      'securityDashboard': 'సెక్యూరిటీ డాష్‌బోర్డ్',
      'dutyStatus': 'డ్యూటీ పరిస్థితి',
      'online': 'ఆన్‌లైన్ అందుబాటులో ఉంది',
      'offline': 'ఆఫ్‌లైన్',
      'acceptIncident': 'ఘటనను స్వీకరించండి',
      'inProgressIncident': 'పురోగతిలో ఉంది',
      'resolveIncident': 'పరిష్కరించండి',
      'viewDetails': 'వివరాలను చూడండి',
      'callResident': 'నివాసికి కాల్ చేయండి',
      'openChat': 'అత్యవసర చాట్ తెరువు',
      'emergencyType': 'అత్యవసర వర్గం',
      'medical': 'వైద్య అత్యవసరం',
      'fire': 'అగ్నిప్రమాదం',
      'security': 'భద్రతా ముప్పు',
      'lift': 'లిఫ్ట్ సమస్య',
      'disaster': 'ప్రకృతి విపత్తు',
      'general': 'సాధారణ అత్యవసరం',
      'recordVoiceMessage': 'వాయిస్ నోట్ రికార్డ్ చేయండి',
      'stopRecording': 'రికార్డింగ్ ఆపండి',
      'confirmSos': 'SOS పంపండి',
      'sosSuccess': 'SOS పంపబడింది!',
      'respondersNotified': 'గార్డియన్లు మరియు సెక్యూరిటీకి సమాచారం అందించబడింది.',
      'societyName': 'సొసైటీ',
      'blockName': 'బ్లాక్',
      'flatNumber': 'ఫ్లాట్',
      'guardianCode': 'గార్డియన్ కోడ్',
      'generateCode': 'కోడ్ జనరేట్ చేయండి',
      'linkGuardian': 'గార్డియన్ లింక్ చేయండి',
      'relationship': 'సంబంధం',
      'primaryGuardian': 'ప్రాథమిక గార్డియన్',
      'secondaryGuardian': 'ద్వితీయ గార్డియన్',
      'emergencyContact': 'అత్యవసర పరిచయం',
      'step1PersonalDetails': 'దశ 1: మీ వ్యక్తిగత వివరాలను నమోదు చేయండి',
      'step2RoleConfig': 'దశ 2: మీ ప్రొఫైల్ పాత్రను ఎంచుకోండి',
      'step3ConfirmDetails': 'దశ 3: వివరాలను నిర్ధారించండి మరియు రిజిస్టర్ చేయండి',
      'fullName': 'పూర్తి పేరు',
      'confirmPassword': 'పాస్‌వర్డ్‌ను నిర్ధారించండి',
      'passwordsDoNotMatch': 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు',
      'chooseYourRole': 'మీ పాత్రను ఎంచుకోండి',
      'residentRole': 'నివాసి',
      'guardianRole': 'గార్డియన్',
      'volunteerRole': 'వాలంటీర్',
      'securityRole': 'సెక్యూరిటీ సిబ్బంది',
      'selectSociety': 'సొసైటీని ఎంచుకోండి',
      'selectBlock': 'బ్లాక్‌ను ఎంచుకోండి',
      'flatApartmentNumber': 'ఫ్లాట్/అపార్ట్‌మెంట్ సంఖ్య',
      'selectRelationship': 'సంబంధాన్ని ఎంచుకోండి',
      'skills': 'నైపుణ్యాలు (ఉదా. మెడికల్, ఫస్ట్ ఎయిడ్)',
      'availability': 'అందుబాటు (ఉదా. వారాంతాల్లో, 24/7)',
      'serviceArea': 'సేవా ప్రాంతం (ఉదా. బ్లాక్ A, ఔటర్)',
      'shift': 'షిఫ్ట్ (ఉదా. డే, నైట్)',
      'employeeId': 'ఉద్యోగి ఐడి',
      'assignedSociety': 'కేటాయించిన సొసైటీ',
      'reviewRegistrationSummary': 'రిజిస్ట్రేషన్ సారాంశాన్ని సమీక్షించండి',
      'agreeTermsText': 'నేను నిబంధనలు & గోప్యతా విధానానికి అంగీకరిస్తున్నాను',
      'addContact': 'అత్యవసర పరిచయాన్ని జోడించండి',
      'addGuardian': 'గార్డియన్‌ను జోడించండి',
      'enterGuardianCode': 'గార్డియన్ కోడ్‌ను నమోదు చేయండి',
    },
    'ta': {
      'appName': 'CareConnect',
      'tagline': 'சமூக அவசரக்கால பதிலளிப்பு மற்றும் உதவி நெட்வொர்க்',
      'subHeading': 'சமூகங்களை பாதுகாப்போம், ஒரே நேரத்தில் ஒரு SOS.',
      'getStarted': 'தொடங்குங்கள்',
      'login': 'உள்நுழைவு',
      'register': 'பதிவுசெய்க',
      'welcomeBack': 'மீண்டும் வருக',
      'email': 'மின்னஞ்சல் முகவரி',
      'password': 'கடவுச்சொல்',
      'rememberMe': 'என்னை நினைவில் கொள்க',
      'forgotPassword': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'createAccount': 'கணக்கை உருவாக்கு',
      'chooseLanguage': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      'selectLanguageSub': 'CareConnect க்கான உங்கள் விருப்ப மொழியைத் தேர்ந்தெடுக்கவும்.',
      'continueText': 'தொடரவும்',
      'oneTapSos': 'ஒன்-டேப் SOS',
      'oneTapSosSub': 'உடனடி அவசர உதவி.',
      'guardianAlerts': 'பாதுகாவலர் எச்சரிக்கைகள்',
      'guardianAlertsSub': 'நம்பகமான பாதுகாவலர்களுக்கு உடனடியாக தெரிவிக்கவும்.',
      'liveGps': 'நேரலை GPS கண்காணிப்பு',
      'liveGpsSub': 'துல்லியமான இடத்தைப் பகிரவும்.',
      'volunteerResponse': 'தன்னார்வலர் பதில்',
      'volunteerResponseSub': 'அருகிலுள்ள தன்னார்வலர்களுக்கு எச்சரிக்கை.',
      'securityCoordination': 'பாதுகாப்பு ஒருங்கிணைப்பு',
      'securityCoordinationSub': 'பாதுகாப்புப் பணியாளர்களுக்கு உடனடி அறிவிப்புகள்.',
      'emergencyChat': 'அவசர அரட்டை',
      'emergencyChatSub': 'அவசர காலத்தில் நேரலை தொடர்பு.',
      'communitySafety': 'சமூக பாதுகாப்பு',
      'communitySafetySub': 'ஒருங்கிணைந்த அவசரக்கால பதில்.',
      'howItWorks': 'இது எவ்வாறு இயங்குகிறது',
      'step1': 'பதிவுசெய்க',
      'step2': 'சமூகத்தில் இணையுங்கள்',
      'step3': 'பாதுகாவலரைச் சேர்க்கவும்',
      'step4': 'SOS ஐ அழுத்தவும்',
      'step5': 'உதவி பெறுங்கள்',
      'settings': 'அமைப்புகள்',
      'language': 'மொழி',
      'privacyPolicy': 'தனியுரிமைக் கொள்கை',
      'termsConditions': 'விதிகள் & நிபந்தனைகள்',
      'version': 'பதிப்பு 1.0.0',
      'description': 'CareConnect அவசர காலத்தில் விரைவான உதவி பெற உதவுகிறது.',
      'home': 'முகப்பு',
      'alerts': 'எச்சரிக்கைகள்',
      'profile': 'சுயவிவரம்',
      'logout': 'வெளியேறு',
      'submit': 'சமர்ப்பி',
      'cancel': 'ரத்துசெய்',
      'save': 'சேமி',
      'close': 'மூடு',
      'back': 'பின்னால்',
      'loading': 'ஏற்றுகிறது...',
      'search': 'தேடு...',
      'error': 'பிழை',
      'success': 'வெற்றி',
      'warning': 'எச்சரிக்கை',
      'info': 'தகவல்',
      'residentDashboard': 'குடியிருப்பாளர் டாஷ்போர்டு',
      'guardianDashboard': 'பாதுகாவலர் டாஷ்போர்டு',
      'volunteerDashboard': 'தன்னார்வலர் டாஷ்போர்டு',
      'securityDashboard': 'பாதுகாப்பு டாஷ்போர்டு',
      'dutyStatus': 'பணி நிலை',
      'online': 'ஆன்லைனில் கிடைக்கிறார்',
      'offline': 'ஆஃப்லைன்',
      'acceptIncident': 'சம்பவத்தை ஏற்றுக்கொள்',
      'inProgressIncident': 'செயல்பாட்டில் உள்ளது',
      'resolveIncident': 'தீர்வு காண்',
      'viewDetails': 'விவரங்களைக் காண்',
      'callResident': 'குடியிருப்பாளரை அழை',
      'openChat': 'அவசர அரட்டையைத் திற',
      'emergencyType': 'அவசர வகை',
      'medical': 'மருத்துவ அவசரம்',
      'fire': 'தீ விபத்து',
      'security': 'பாதுகாப்பு அச்சுறுத்தல்',
      'lift': 'மின்தூக்கி கோளாறு',
      'disaster': 'இயற்கை பேரழிவு',
      'general': 'பொது அவசரம்',
      'recordVoiceMessage': 'குரல் பதிவு செய்',
      'stopRecording': 'பதிவை நிறுத்து',
      'confirmSos': 'SOS அனுப்பு',
      'sosSuccess': 'SOS அனுப்பப்பட்டது!',
      'respondersNotified': 'பாதுகாவலர்களுக்கு எச்சரிக்கை அனுப்பப்பட்டது.',
      'societyName': 'சமூகம்',
      'blockName': 'பிளாக்',
      'flatNumber': 'பிளாட்',
      'guardianCode': 'பாதுகாவலர் குறியீடு',
      'generateCode': 'குறியீட்டை உருவாக்கு',
      'linkGuardian': 'பாதுகாவலரை இணை',
      'relationship': 'உறவு',
      'primaryGuardian': 'முதன்மை பாதுகாவலர்',
      'secondaryGuardian': 'இரண்டாம் நிலை பாதுகாவலர்',
      'emergencyContact': 'அவசர தொடர்பு',
    },
    'kn': {
      'appName': 'CareConnect',
      'tagline': 'ಸಮುದಾಯ ತುರ್ತು ಸ್ಪಂದನೆ ಮತ್ತು ನೆರವು ಜಾಲ',
      'subHeading': 'ಸಮುದಾಯಗಳ ರಕ್ಷಣೆ, ಒಮ್ಮೆಗೆ ಒಂದು SOS.',
      'getStarted': 'ಪ್ರಾರಂಭಿಸಿ',
      'login': 'ಲಾಗಿನ್',
      'register': 'ನೋಂದಾಯಿಸಿ',
      'welcomeBack': 'ಸ್ವಾಗತ',
      'email': 'ಇಮೇಲ್ ವಿಳಾಸ',
      'password': 'ಪಾಸ್‌ವರ್ಡ್',
      'rememberMe': 'ನನ್ನನ್ನು ನೆನಪಿಡಿ',
      'forgotPassword': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?',
      'createAccount': 'ಖಾತೆ ರಚಿಸಿ',
      'chooseLanguage': 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'selectLanguageSub': 'CareConnect ಗಾಗಿ ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
      'continueText': 'ಮುಂದುವರಿಸಿ',
      'oneTapSos': 'ಒನ್-ಟ್ಯಾಪ್ SOS',
      'oneTapSosSub': 'ತಕ್ಷಣದ ತುರ್ತು ನೆರವು.',
      'guardianAlerts': 'ಪೋಷಕರ ಎಚ್ಚರಿಕೆಗಳು',
      'guardianAlertsSub': 'ತಕ್ಷಣ ಪೋಷಕರಿಗೆ ತಿಳಿಸಿ.',
      'liveGps': 'ಲೈವ್ GPS ಟ್ರ್ಯಾಕಿಂಗ್',
      'liveGpsSub': 'ನಿಖರವಾದ ಸ್ಥಳವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ.',
      'volunteerResponse': 'ಸ್ವಯಂಸೇವಕರ ಸ್ಪಂದನೆ',
      'volunteerResponseSub': 'ಸಮೀಪದ ಸ್ವಯಂಸೇವಕರಿಗೆ ಎಚ್ಚರಿಕೆ.',
      'securityCoordination': 'ಭದ್ರತಾ ಸಮನ್ವಯ',
      'securityCoordinationSub': 'ಭದ್ರತಾ ಸಿಬ್ಬಂದಿಗೆ ತಕ್ಷಣದ ಮಾಹಿತಿ.',
      'emergencyChat': 'ತುರ್ತು ಚಾಟ್',
      'emergencyChatSub': 'ತುರ್ತು ಸಮಯದಲ್ಲಿ ಲೈವ್ ಸಂವಹನ.',
      'communitySafety': 'ಸಮುದಾಯ ಸುರಕ್ಷತೆ',
      'communitySafetySub': 'ಸಂಯೋಜಿತ ತುರ್ತು ಸ್ಪಂದನೆ.',
      'howItWorks': 'ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ',
      'step1': 'ನೋಂದಾಯಿಸಿ',
      'step2': 'ಸೊಸೈಟಿಗೆ ಸೇರಿ',
      'step3': 'ಪೋಷಕರನ್ನು ಸೇರಿಸಿ',
      'step4': 'SOS ಒತ್ತಿ',
      'step5': 'ಸಹಾಯ ಪಡೆಯಿರಿ',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'language': 'ಭಾಷೆ',
      'privacyPolicy': 'ಗೌಪ್ಯತಾ ನೀತಿ',
      'termsConditions': 'ನಿಯಮಗಳು & ಷರತ್ತುಗಳು',
      'version': 'ಆವೃತ್ತಿ 1.0.0',
      'description': 'CareConnect ತುರ್ತು ಸಂದರ್ಭಗಳಲ್ಲಿ ತಕ್ಷಣದ ನೆರವು ನೀಡುತ್ತದೆ.',
      'home': 'ಮುಖಪುಟ',
      'alerts': 'ಎಚ್ಚರಿಕೆಗಳು',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'submit': 'ಸಲ್ಲಿಸಿ',
      'cancel': 'ರದ್ದುಗೊಳಿಸಿ',
      'save': 'ಉಳಿಸಿ',
      'close': 'ಮುಚ್ಚಿ',
      'back': 'ಹಿಂತಿರುಗಿ',
      'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      'search': 'ಹುಡುಕಿ...',
      'error': 'ದೋಷ',
      'success': 'ಯಶಸ್ಸು',
      'warning': 'ಎಚ್ಚರಿಕೆ',
      'info': 'ಮಾಹಿತಿ',
      'residentDashboard': 'ನಿವಾಸಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'guardianDashboard': 'ಪೋಷಕರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'volunteerDashboard': 'ಸ್ವಯಂಸೇವಕರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'securityDashboard': 'ಭದ್ರತಾ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'dutyStatus': 'ಕರ್ತವ್ಯ ಸ್ಥಿತಿ',
      'online': 'ಆನ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದಾರೆ',
      'offline': 'ಆಫ್‌ಲೈನ್',
      'acceptIncident': 'ಘಟನೆಯನ್ನು ಸ್ವೀಕರಿಸಿ',
      'inProgressIncident': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
      'resolveIncident': 'ಪರಿಹರಿಸಿ',
      'viewDetails': 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
      'callResident': 'ನಿವಾಸಿಗೆ ಕರೆ ಮಾಡಿ',
      'openChat': 'ತುರ್ತು ಚಾಟ್ ತೆರೆಯಿರಿ',
      'emergencyType': 'ತುರ್ತು ವರ್ಗ',
      'medical': 'ವೈದ್ಯಕೀಯ ತುರ್ತು',
      'fire': 'ಬೆಂಕಿ ಅವಘಡ',
      'security': 'ಭದ್ರತಾ ಬೆದರಿಕೆ',
      'lift': 'ಲಿಫ್ಟ್ ಸಮಸ್ಯೆ',
      'disaster': 'ನೈಸರ್ಗಿಕ ವಿಕೋಪ',
      'general': 'ಸಾಮಾನ್ಯ ತುರ್ತು',
      'recordVoiceMessage': 'ಧ್ವನಿ ಟಿಪ್ಪಣಿ ರೆಕಾರ್ಡ್ ಮಾಡಿ',
      'stopRecording': 'ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ',
      'confirmSos': 'SOS ಕಳುಹಿಸಿ',
      'sosSuccess': 'SOS ಕಳುಹಿಸಲಾಗಿದೆ!',
      'respondersNotified': 'ಪೋಷಕರಿಗೆ ಎಚ್ಚರಿಕೆ ತಲುಪಿಸಲಾಗಿದೆ.',
      'societyName': 'ಸೊಸೈಟಿ',
      'blockName': 'ಬ್ಲಾಕ್',
      'flatNumber': 'ಫ್ಲಾಟ್',
      'guardianCode': 'ಪೋಷಕರ ಕೋಡ್',
      'generateCode': 'ಕೋಡ್ ರಚಿಸಿ',
      'linkGuardian': 'ಪೋಷಕರನ್ನು ಲಿಂಕ್ ಮಾಡಿ',
      'relationship': 'ಸಂಬಂಧ',
      'primaryGuardian': 'ಪ್ರಾಥಮಿಕ ಪೋಷಕರು',
      'secondaryGuardian': 'ದ್ವಿತೀಯ ಪೋಷಕರು',
      'emergencyContact': 'ತುರ್ತು ಸಂಪರ್ಕ',
    },
    'ml': {
      'appName': 'CareConnect',
      'tagline': 'കമ്മ്യൂണിറ്റി എമർജൻസി റെസ്പോൺസ് & അസിസ്റ്റൻസ് നെറ്റ്‌വർക്ക്',
      'subHeading': 'സമൂഹത്തിന്റെ സംരക്ഷണം, ഒരു സമയത്ത് ഒരു SOS.',
      'getStarted': 'ആരംഭിക്കുക',
      'login': 'ലോഗിൻ',
      'register': 'രജിസ്റ്റർ ചെയ്യുക',
      'welcomeBack': 'സ്വാഗതം',
      'email': 'ഇമെയിൽ വിലാസം',
      'password': 'പാസ്‌വേഡ്',
      'rememberMe': 'എന്നെ ഓർക്കുക',
      'forgotPassword': 'പാസ്‌വേഡ് മറന്നോ?',
      'createAccount': 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
      'chooseLanguage': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'selectLanguageSub': 'CareConnect-നായി നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക.',
      'continueText': 'തുടരുക',
      'oneTapSos': 'വൺ-ടാപ്പ് SOS',
      'oneTapSosSub': 'ഉടനടിയുള്ള അടിയന്തര സഹായം.',
      'guardianAlerts': 'രക്ഷിതാക്കളുടെ അലേർട്ടുകൾ',
      'guardianAlertsSub': 'രക്ഷിതാക്കളെ ഉടൻ അറിയിക്കുക.',
      'liveGps': 'ലൈവ് GPS ട്രെയ്ക്കിംഗ്',
      'liveGpsSub': 'കൃത്യമായ ലൊക്കേഷൻ പങ്കിടുക.',
      'volunteerResponse': 'വോളന്റിയർ പ്രതികരണം',
      'volunteerResponseSub': 'സമീപത്തുള്ള വോളന്റിയർമാർക്ക് അലേർട്ട്.',
      'securityCoordination': 'സെക്യൂരിറ്റി കോർഡിനേഷൻ',
      'securityCoordinationSub': 'സെക്യൂരിറ്റി ജീവനക്കാർക്ക് അടിയന്തര സന്ദേശം.',
      'emergencyChat': 'അടിയന്തര ചാറ്റ്',
      'emergencyChatSub': 'അടിയന്തിര ഘട്ടങ്ങളിൽ ലൈവ് ചാറ്റ്.',
      'communitySafety': 'കമ്മ്യൂണിറ്റി സുരക്ഷ',
      'communitySafetySub': 'ഏകോപിപ്പിച്ച അടിയന്തര പ്രതികരണം.',
      'howItWorks': 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
      'step1': 'രജിസ്റ്റർ ചെയ്യുക',
      'step2': 'സൊസൈറ്റിയിൽ ചേരുക',
      'step3': 'രക്ഷിതാക്കളെ ചേർക്കുക',
      'step4': 'SOS അമർത്തുക',
      'step5': 'സഹായം നേടുക',
      'settings': 'ക്രമീകരണങ്ങൾ',
      'language': 'ഭാഷ',
      'privacyPolicy': 'സ്വകാര്യതാ നയം',
      'termsConditions': 'നിബന്ധനകളും വ്യവസ്ഥകളും',
      'version': 'പതിപ്പ് 1.0.0',
      'description': 'CareConnect അടിയന്തിര ഘട്ടങ്ങളിൽ അതിവേഗ സഹായം ഉറപ്പാക്കുന്നു.',
      'home': 'ഹോം',
      'alerts': 'അലേർട്ടുകൾ',
      'profile': 'പ്രൊഫൈൽ',
      'logout': 'ലോഗ് ഔട്ട്',
      'submit': 'സമർപ്പിക്കുക',
      'cancel': 'റദ്ദാക്കുക',
      'save': 'സേവ് ചെയ്യുക',
      'close': 'അടയ്ക്കുക',
      'back': 'പിന്നോട്ട്',
      'loading': 'ലോഡ് ചെയ്യുന്നു...',
      'search': 'തിരയുക...',
      'error': 'പിശക്',
      'success': 'വിജയം',
      'warning': 'മുന്നറിയിപ്പ്',
      'info': 'വിവരം',
      'residentDashboard': 'റസിഡന്റ് ഡാഷ്‌ബോർഡ്',
      'guardianDashboard': 'ഗാർഡിയൻ ഡാഷ്‌ബോർഡ്',
      'volunteerDashboard': 'വോളന്റിയർ ഡാഷ്‌ബോർഡ്',
      'securityDashboard': 'സെക്യൂരിറ്റി ഡാഷ്‌ബോർഡ്',
      'dutyStatus': 'ഡ്യൂട്ടി അവസ്ഥ',
      'online': 'ഓൺലൈനിൽ ലഭ്യമാണ്',
      'offline': 'ഓഫ്‌ലൈൻ',
      'acceptIncident': 'സംഭവം സ്വീകരിക്കുക',
      'inProgressIncident': 'പുരോഗമിക്കുന്നു',
      'resolveIncident': 'പരിഹരിക്കുക',
      'viewDetails': 'വിശദാംശങ്ങൾ കാണുക',
      'callResident': 'റസിഡന്റിനെ വിളിക്കുക',
      'openChat': 'അടിയന്തര ചാറ്റ് തുറക്കുക',
      'emergencyType': 'അടിയന്തര വിഭാഗം',
      'medical': 'മെഡിക്കൽ അടിയന്തരാവസ്ഥ',
      'fire': 'തീപിടുത്തം',
      'security': 'സുരക്ഷാ ഭീഷണി',
      'lift': 'ലിഫ്റ്റ് തകരാർ',
      'disaster': 'പ്രകൃതിദുരന്തം',
      'general': 'പൊതു അടിയന്തരാവസ്ഥ',
      'recordVoiceMessage': 'വോയ്സ് നോട്ട് റെക്കോർഡ് ചെയ്യുക',
      'stopRecording': 'റെക്കോർഡിംഗ് നിർത്തുക',
      'confirmSos': 'SOS അയക്കുക',
      'sosSuccess': 'SOS അയച്ചു!',
      'respondersNotified': 'രക്ഷിതാക്കൾക്ക് മുന്നറിയിപ്പ് നൽകി.',
      'societyName': 'സൊസൈറ്റി',
      'blockName': 'ബ്ലോക്ക്',
      'flatNumber': 'ഫ്ലാറ്റ്',
      'guardianCode': 'ഗാർഡിയൻ കോഡ്',
      'generateCode': 'കോഡ് ജനറേറ്റ് ചെയ്യുക',
      'linkGuardian': 'ഗാർഡിയനെ ലിങ്ക് ചെയ്യുക',
      'relationship': 'ബന്ധം',
      'primaryGuardian': 'പ്രാഥമിക ഗാർഡിയൻ',
      'secondaryGuardian': 'ദ്വിതീയ ഗാർഡിയൻ',
      'emergencyContact': 'അടിയന്തര കോൺടാക്റ്റ്',
    },
    'ar': {
      'appName': 'CareConnect',
      'tagline': 'شبكة الاستجابة والمساعدة في حالات الطوارئ المجتمعية',
      'subHeading': 'حماية المجتمعات، نداء نجدة واحد في كل مرة.',
      'getStarted': 'البدء',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'welcomeBack': 'مرحباً بعودتك',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'rememberMe': 'تذكرني',
      'forgotPassword': 'هل نسيت كلمة المرور؟',
      'createAccount': 'إنشاء حساب جديد',
      'chooseLanguage': 'اختر لغتك',
      'selectLanguageSub': 'اختر لغتك المفضلة لتطبيق CareConnect.',
      'continueText': 'متابعة',
      'oneTapSos': 'نداء نجدة بضغطة واحدة',
      'oneTapSosSub': 'مساعدة طوارئ فورية في متناول يديك.',
      'guardianAlerts': 'تنبيهات الأولياء',
      'guardianAlertsSub': 'إبلاغ أولياء الأمور الموثوقين فوراً.',
      'liveGps': 'تتبع الموقع المباشر',
      'liveGpsSub': 'مشاركة موقع الطوارئ الدقيق في الوقت الفعلي.',
      'volunteerResponse': 'استجابة المتطوعين',
      'volunteerResponseSub': 'يتلقى المتطوعون القريبون تنبيهات فورية.',
      'securityCoordination': 'تنسيق الأمن',
      'securityCoordinationSub': 'يتلقى أفراد الأمن إشعارات فورية.',
      'emergencyChat': 'محادثة الطوارئ',
      'emergencyChatSub': 'تواصل مباشر في الوقت الفعلي أثناء الطوارئ.',
      'communitySafety': 'سلامة المجتمع',
      'communitySafetySub': 'استجابة طوارئ مجتمعية متكاملة.',
      'howItWorks': 'كيف يعمل التطبيق',
      'step1': 'التسجيل',
      'step2': 'الانضمام للمجمع',
      'step3': 'إضافة الأولياء',
      'step4': 'ضغط نداء النجدة',
      'step5': 'تلقي المساعدة',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'privacyPolicy': 'سياسة الخصوصية',
      'termsConditions': 'الشروط والأحكام',
      'version': 'الإصدار 1.0.0',
      'description': 'يمكّن CareConnect السكان وأولياء الأمور والمتطوعين ورجال الأمن من الاستجابة السريعة أثناء الطوارئ.',
      'home': 'الرئيسية',
      'alerts': 'التنبيهات',
      'profile': 'الملف الشخصي',
      'logout': 'تسجيل الخروج',
      'submit': 'إرسال',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'close': 'إغلاق',
      'back': 'رجوع',
      'loading': 'جاري التحميل...',
      'search': 'بحث...',
      'error': 'خطأ',
      'success': 'نجاح',
      'warning': 'تحذير',
      'info': 'معلومات',
      'residentDashboard': 'لوحة الساكن',
      'guardianDashboard': 'لوحة الولي',
      'volunteerDashboard': 'لوحة المتطوع',
      'securityDashboard': 'لوحة الأمن',
      'dutyStatus': 'حالة المناوبة',
      'online': 'متصل وجاهز',
      'offline': 'غير متصل',
      'acceptIncident': 'قبول البلاغ',
      'inProgressIncident': 'قيد المعالجة',
      'resolveIncident': 'إغلاق البلاغ',
      'viewDetails': 'عرض التفاصيل',
      'callResident': 'الاتصال بالساكن',
      'openChat': 'فتح المحادثة',
      'emergencyType': 'فئة الطوارئ',
      'medical': 'طوارئ طبية',
      'fire': 'حريق',
      'security': 'تهديد أمني',
      'lift': 'تعطل المصعد',
      'disaster': 'كارثة طبيعية',
      'general': 'طوارئ عامة',
      'recordVoiceMessage': 'تسجيل ملاحظة صوتية',
      'stopRecording': 'إيقاف التسجيل',
      'confirmSos': 'تأكيد نداء النجدة',
      'sosSuccess': 'تم إرسال نداء النجدة!',
      'respondersNotified': 'تم تنبيه الأولياء والأمن.',
      'societyName': 'المجمع',
      'blockName': 'المبنى',
      'flatNumber': 'الشقة',
      'guardianCode': 'رمز الولي',
      'generateCode': 'إنشاء رمز',
      'linkGuardian': 'ربط ولي أمر',
      'relationship': 'صلة القرابة',
      'primaryGuardian': 'الولي الرئيسي',
      'secondaryGuardian': 'الولي الثانوي',
      'emergencyContact': 'جهة اتصال الطوارئ',
    },
  };

  String translate(String key) {
    final langCode = locale.languageCode;
    if (_localizedValues.containsKey(langCode) &&
        _localizedValues[langCode]!.containsKey(key)) {
      return _localizedValues[langCode]![key]!;
    }
    // Fallback to English dictionary
    return _localizedValues['en']?[key] ?? key;
  }

  // Type-safe property getters for standard Flutter localization usage
  String get appName => translate('appName');
  String get tagline => translate('tagline');
  String get subHeading => translate('subHeading');
  String get getStarted => translate('getStarted');
  String get login => translate('login');
  String get register => translate('register');
  String get welcomeBack => translate('welcomeBack');
  String get email => translate('email');
  String get password => translate('password');
  String get rememberMe => translate('rememberMe');
  String get forgotPassword => translate('forgotPassword');
  String get createAccount => translate('createAccount');
  String get chooseLanguage => translate('chooseLanguage');
  String get selectLanguageSub => translate('selectLanguageSub');
  String get continueText => translate('continueText');
  String get oneTapSos => translate('oneTapSos');
  String get oneTapSosSub => translate('oneTapSosSub');
  String get guardianAlerts => translate('guardianAlerts');
  String get guardianAlertsSub => translate('guardianAlertsSub');
  String get liveGps => translate('liveGps');
  String get liveGpsSub => translate('liveGpsSub');
  String get volunteerResponse => translate('volunteerResponse');
  String get volunteerResponseSub => translate('volunteerResponseSub');
  String get securityCoordination => translate('securityCoordination');
  String get securityCoordinationSub => translate('securityCoordinationSub');
  String get emergencyChat => translate('emergencyChat');
  String get emergencyChatSub => translate('emergencyChatSub');
  String get communitySafety => translate('communitySafety');
  String get communitySafetySub => translate('communitySafetySub');
  String get howItWorks => translate('howItWorks');
  String get step1 => translate('step1');
  String get step2 => translate('step2');
  String get step3 => translate('step3');
  String get step4 => translate('step4');
  String get step5 => translate('step5');
  String get settings => translate('settings');
  String get language => translate('language');
  String get privacyPolicy => translate('privacyPolicy');
  String get termsConditions => translate('termsConditions');
  String get version => translate('version');
  String get description => translate('description');

  String get home => translate('home');
  String get alerts => translate('alerts');
  String get profile => translate('profile');
  String get logout => translate('logout');
  String get submit => translate('submit');
  String get cancel => translate('cancel');
  String get save => translate('save');
  String get close => translate('close');
  String get back => translate('back');
  String get loading => translate('loading');
  String get search => translate('search');
  String get error => translate('error');
  String get success => translate('success');
  String get warning => translate('warning');
  String get info => translate('info');

  String get residentDashboard => translate('residentDashboard');
  String get guardianDashboard => translate('guardianDashboard');
  String get volunteerDashboard => translate('volunteerDashboard');
  String get securityDashboard => translate('securityDashboard');
  String get adminDashboard => translate('adminDashboard');
  String get societyManager => translate('societyManager');
  String get dutyStatus => translate('dutyStatus');
  String get online => translate('online');
  String get offline => translate('offline');
  String get acceptIncident => translate('acceptIncident');
  String get inProgressIncident => translate('inProgressIncident');
  String get resolveIncident => translate('resolveIncident');
  String get viewDetails => translate('viewDetails');
  String get callResident => translate('callResident');
  String get openChat => translate('openChat');
  String get responseFeed => translate('responseFeed');

  String get emergencyType => translate('emergencyType');
  String get medical => translate('medical');
  String get fire => translate('fire');
  String get security => translate('security');
  String get lift => translate('lift');
  String get disaster => translate('disaster');
  String get general => translate('general');
  String get recordVoiceMessage => translate('recordVoiceMessage');
  String get stopRecording => translate('stopRecording');
  String get playVoiceMessage => translate('playVoiceMessage');
  String get deleteVoiceMessage => translate('deleteVoiceMessage');
  String get currentLocation => translate('currentLocation');
  String get confirmSos => translate('confirmSos');
  String get sosSuccess => translate('sosSuccess');
  String get respondersNotified => translate('respondersNotified');

  String get societyName => translate('societyName');
  String get blockName => translate('blockName');
  String get flatNumber => translate('flatNumber');
  String get guardianCode => translate('guardianCode');
  String get generateCode => translate('generateCode');
  String get linkGuardian => translate('linkGuardian');
  String get relationship => translate('relationship');
  String get primaryGuardian => translate('primaryGuardian');
  String get secondaryGuardian => translate('secondaryGuardian');
  String get emergencyContact => translate('emergencyContact');
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .map((e) => e.languageCode)
        .contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
