# Generated by Django 5.0.6 on 2026-07-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emergency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencycontact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
